### PR TITLE
Updated process_report.py to avoid warnings for SettingWithCopyWarnings and FutureWarnings

### LINKED ISSUE #34: Some warnings I saw when I ran the scripts to produce the report for April
Just wanted to document these.

```
Invoice date: 2024-04
The following timed-projects will not be billed for this period:

<line intentionally removed>

/Users/naved/office-stuff/process_csv_report/process_report/process_report.py:406: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Boston University' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  dataframe.at[i, INSTITUTION_FIELD] = get_institution_from_pi(

<lots of lines about project not having a PI>

/Users/naved/office-stuff/process_csv_report/process_report/process_report.py:442: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  BU_projects["Project"] = BU_projects.apply(get_project, axis=1)
/Users/naved/office-stuff/process_csv_report/process_report/process_report.py:443: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  BU_projects[SUBSIDY_FIELD] = 0
/Users/naved/office-stuff/process_csv_report/process_report/process_report.py:469: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '84.270' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  dataframe.at[i, SUBSIDY_FIELD] = applied_subsidy
  ```

### PR DESCRIPTION
**Pull request by QuanMPhm**
Closes #34, I've added a few small changes which should remove all pandas SettingWithCopyWarning and FutureWarning warnings. These consisted of explicit type casting, and explicitly making copies of data-frames that would later be modified

### CODE REVIEW

**Review by larsks — COMMENTED** [review]
I'm not sure I understand the relationship between the title of this PR ("Patched pandas warnings for SettingWithCopyWarnings and FutureWarnings") and the changes it contains.

**Comment by QuanMPhm** [comment]
@larsks Without the changes, running the processing script will make Pandas print the 2 warnings mentioned in the title. The SettingWithCopyWarnings came from the fact that I was performing [chained indexing](https://pandas.pydata.org/docs/user_guide/indexing.html#returning-a-view-versus-a-copy) on a few dataframes. Since chained indexing may return a copy of the dataframe or dataframe itself, this causes ambiguity on whether assignments to the indexed dataframes would change the original, or merely a copy. I resolved the warnings by explicitly using the `copy()` function to make copies of the dataframes.

As for the FutureWarnings, these were caused by assigning strings to empty columns, whose values default to NaN (float). Since float is incompatible with strings, this raises a warning.

**Comment by larsks** [comment]
Ah, so "Update code to avoid SettingWithCopyWarnings and FutureWarnings".

**Comment by QuanMPhm** [comment]
@naved001 I've updated the commit message

**Review by naved001 — APPROVED** [review]

**Review by larsks — APPROVED** [review]

**Pull request merged**
